export const TOGGLE_BOXED_LAYOUT = 'TOGGLE_BOXED_LAYOUT';
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSED_NAV';
export const TOGGLE_NAV_BEHIND = 'TOGGLE_NAV_BEHIND';
export const TOGGLE_FIXED_HEADER = 'TOGGLE_FIXED_HEADER';
export const CHANGE_SIDEBAR_WIDTH = 'CHANGE_SIDEBAR_WIDTH';
export const CHANGE_COLOR_OPTION = 'CHANGE_COLOR_OPTION';
export const CHANGE_THEME = 'CHANGE_THEME';

export const FETCH_RESERVATIONS = "FETCH_RESERVATIONS";
export const FETCH_RESERVATIONS_SUCCESS = "FETCH_RESERVATIONS_SUCCESS";
export const FETCH_RESERVATIONS_ERROR = "FETCH_RESERVATIONS_ERROR";
export const SET_RESERVATION_DATE = "SET_RESERVATION_DATE";
export const SET_RESERVATION_DATE_SUCCESS = "SET_RESERVATION_DATE_SUCCESS";
export const SET_RESERVATION_DATE_ERROR = "SET_RESERVATION_DATE_ERROR";
export const SET_PAYMENT_DATE = "SET_PAYMENT_DATE";
export const SET_PAYMENT_DATE_SUCCESS = "SET_PAYMENT_DATE_SUCCESS";
export const SET_PAYMENT_DATE_ERROR = "SET_PAYMENT_DATE_ERROR";
export const SET_SENT_PACKAGE_DATE = "SET_SENT_PACKAGE_DATE";
export const SET_SENT_PACKAGE_DATE_SUCCESS = "SET_SENT_PACKAGE_DATE_SUCCESS";
export const SET_SENT_PACKAGE_DATE_ERROR = "SET_SENT_PACKAGE_DATE_ERROR";
export const SET_AGENT_CALLED_DATE = "SET_AGENT_CALLED_DATE";
export const SET_AGENT_CALLED_DATE_SUCCESS = "SET_AGENT_CALLED_DATE_SUCCESS";
export const SET_AGENT_CALLED_DATE_ERROR = "SET_AGENT_CALLED_DATE_ERROR";

